### ISSUE TITLE
settings for the best results

### ISSUE THREAD

**Issue by deeplearningmachine** [unilight/R-NET-in-Tensorflow#3] opened 2017-11-29 03:18 UTC
I just wonder what were your configurations for getting the best results of 62.6 and 71.5?
I used the default settings of your codes and can only obtain 48F1.

**Comment by unilight** [comment] 2017-12-08 08:55
Hi @deeplearningmachine,

Sorry for the late response. First of all, thank you for your attention on my reproduction!
I checked the released configuration and compared it to my experimental setting. Initially I think the difference lies in the number of training epochs. You may set a higher limit of training epoch to maybe 30, 40 or 50 and see when the model starts to overfit. Also, I will rerun the experiment under the setting I reported, and try to find out what I was missing.

edit: I reran the experiment using default settings from this repo, and after 5 training epochs I got 51.1 F1 score.

**Comment by unilight** [comment] 2017-12-10 14:33
Hi @deeplearningmachine,

Thanks to Yang Fan from CAS, I found that there was some ambiguity in the readme file. When evaluating, you need to specify the model path. I have added instruction on how to achieve this. Check it out and let me know if you can get your models evaluated correctly!

**Comment by unilight** [comment] 2018-03-09 05:01
I 'm closing this because I've released a set of trained weight parameters.

**Closed as completed** 2018-03-09 05:03 UTC
Labels: waiting for response
